ALTER TABLE tareas ADD COLUMN ex_miembro BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tareas ADD COLUMN eliminado BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tareas ADD COLUMN fecha_eliminacion TIMESTAMP;
