spring.application.name=tareas_domesticas_backend

spring.datasource.url=jdbc:postgresql://localhost:5432/tareas_domesticas
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true